// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {db} from '../models';

export function ExportEntriesJSON(arg1:api.EntryFilters):Promise<Array<db.LedgerEntry>>;

export function GetAppVersion():Promise<string>;

export function GetEntry(arg1:string):Promise<db.LedgerEntry>;

export function GetIngestionURL():Promise<string>;

export function GetStats(arg1:api.EntryFilters):Promise<api.StatsResult>;

export function IssueKey(arg1:string):Promise<api.IssueKeyResult>;

export function ListKeys():Promise<Array<db.AgentKey>>;

export function Quit():Promise<void>;

export function RevokeKey(arg1:string):Promise<void>;

export function SearchEntries(arg1:api.EntryFilters,arg2:number,arg3:number):Promise<api.SearchResult>;
