// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportEntriesJSON(arg1) {
  return window['go']['main']['App']['ExportEntriesJSON'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetEntry(arg1) {
  return window['go']['main']['App']['GetEntry'](arg1);
}

export function GetIngestionURL() {
  return window['go']['main']['App']['GetIngestionURL']();
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function IssueKey(arg1) {
  return window['go']['main']['App']['IssueKey'](arg1);
}

export function ListKeys() {
  return window['go']['main']['App']['ListKeys']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RevokeKey(arg1) {
  return window['go']['main']['App']['RevokeKey'](arg1);
}

export function SearchEntries(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchEntries'](arg1, arg2, arg3);
}
